# yaml-language-server: $schema=/tmp/ibek.ioc.schema.json

ioc_name: "{{ ioc_yaml_file_name }}"

description: Example ADS driver IOC

entities:
  - type: devIocStats.iocAdminSoft
    IOC: "{{ ioc_name | upper }}"

  - type: adsDriver.AdsSetLocalAMSNetID
    name: ads_net_id
    ams_net_id: "192.168.1.45.1.1"

  - type: adsDriver.AdsOpen
    name: ads
    PORT: ADS
    remote_ip_address: "192.168.1.45"
    remote_ams_net_id: "192.168.1.45.1.1"
