# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 3.2.2
_src_path: gh:epics-containers/ioc-template
description: EPICS Generic IOC for controlling Beckhoff ADS devices
git_platform: github.com
github_org: ulrikpedersen
name: ioc-ads
repo_uri: git@github.com:ulrikpedersen/ioc-ads.git
